### ISSUE TITLE
App crashes if pressing on fab button while refresh is in progress

### ISSUE THREAD

**Issue by huynguyenwork86** [JoaquimLey/bus-eta#57] opened 2018-06-28 12:38 UTC
**Describe the bug**

**To Reproduce**
1. Launch the app. Wait until the loading of bus list finished.
2. Swipe to refresh.
3. While the loading view is still displaying, press the fab icon at the bottom right corner
4. App crashes.

**Expected behavior**
App should not crash

**Smartphone (please complete the following information):**
 - Device: HTC one
 - OS: Android 6.0

**Comment by JoaquimLey** [comment] 2018-06-28 15:01
Hi, @huynguyenwork86 thanks for filing this issue!

Just a couple more things:

- What branch did you compile from?

- Would you be so kind to post the `stacktrace`?

The app is still under heavy development, not even `alpha` but you might've found a bug, appreciate it :)

**Comment by JoaquimLey** [comment] 2018-09-08 16:26
Tested, can't reproduce, closing.

**Closed as completed by JoaquimLey** 2018-09-08 16:26 UTC
Labels: Type: Bug, Priority: Medium, Invalid: Can't reproduce
